spring:
    config:
        import: "optional:file:.env[.properties]"
    application:
        name: wiresentinel
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://db:5432/wiresentinel
        username: sa
        password:
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        properties:
            hibernate:
                hbm2ddl:
                    auto: update
                format_sql: true
        defer-datasource-initialization: true
server:
    address: 0.0.0.0
    port: 8080
jwt:
    secret: ${JWT_SECRET}
wiresentinel:
    sharedkey: ${WIRESENTINEL_SECRET}

